// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcuKRnFbyBzBuvs40Y_Ke6ZRoFuPbtYKc',
    appId: '1:591032139844:web:7e7d8b59ad2fe7ed89fc11',
    messagingSenderId: '591032139844',
    projectId: 'tito-groups',
    authDomain: 'tito-groups.firebaseapp.com',
    storageBucket: 'tito-groups.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJhPCDa-NhAUzBEo1ioEVuyv1MOeljEg',
    appId: '1:591032139844:android:8a6b47dbbed57d9d89fc11',
    messagingSenderId: '591032139844',
    projectId: 'tito-groups',
    storageBucket: 'tito-groups.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlZpHj2oUtCnUp0bMwW99HUnwEIl6jn4Q',
    appId: '1:591032139844:ios:39832239abafeef789fc11',
    messagingSenderId: '591032139844',
    projectId: 'tito-groups',
    storageBucket: 'tito-groups.appspot.com',
    iosClientId:
        '591032139844-uhnrmrv9b3jo1heu3s6e3n7u4m0rrivr.apps.googleusercontent.com',
    iosBundleId: 'com.tito.Groups',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlZpHj2oUtCnUp0bMwW99HUnwEIl6jn4Q',
    appId: '1:591032139844:ios:c056e8f072fcede989fc11',
    messagingSenderId: '591032139844',
    projectId: 'tito-groups',
    storageBucket: 'tito-groups.appspot.com',
    iosClientId:
        '591032139844-3gkgs5shgohbaf5e80h2e03tc8ej6up8.apps.googleusercontent.com',
    iosBundleId: 'com.example.titoGroups',
  );
}
